name: Kelley Bass Jackson
favicon: null
layout_spectrum: 0.07953150919638574
typography_spectrum: 0.34690027008764446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8036449872888625
  lightness: 0.9125528016593307
  saturation: 0.2845712723210454
  rhythmicContrast: 0.04047987167723477
purpose: []
