name: Kelley Bass Jackson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34690027008764446
title: Professional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d2017'
    - '#848d8a'
    - '#b5c0bc'
    - '#5a6360'
    - '#e3878a'
  brandStrength: 0.8036449872888625
  lightness: 0.9125528016593307
  saturation: 0.2845712723210454
  rhythmicContrast: 0.04047987167723477
purpose: []
