typography_spectrum: 0.4452202
color:
  saturation: 0.2845712723210454
  brandStrength: 0.8036449872888625
  lightness: 0.9125528016593307
  brandColors:
    - '#FFF3EA'
    - '#222023'
    - '#C2947C'
    - '#584F46'
    - '#DAD0C7'
  rhythmicContrast: 0.04047987167723477
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: Kelley Bass Jackson
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Multimedia Content Producer
description: I am a story artist.
purpose: []
